name: Bug report
title: '[Bug] short description'
description: Report an Bug
labels: enhancement
body:

- type: input
  id: image
  attributes:
    label: The Minecraft server image
    description: "The image of the Minecraft server."
    placeholder: "vanilla-1.16.5-ibm-semeru-runtimes-8-latest"
  validations:
    required: true
   
- type: textarea
  id: produce
  attributes:
    label: Reproduce bug
    description: "How we can reproduce the bug."
  validations:
    required: true
    
- type: textarea
  id: solution
  attributes:
    label: Solution
    description: "A possible solution."
  validations:
    required: false
